spring:
  profiles:
    include: aws
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: true
  thymeleaf:
    cache: 'false'
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 원하는 파일 크기로 설정
      max-request-size: 10MB  # 원하는 요청 크기로 설정
  data:
    redis:
      host: 1.231.8.249
      port: 6379