spring:
  thymeleaf:
    cache: 'false'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

cloud:
  aws:
    s3:
      bucket: springboot-img
    stack:
      auto-: 'false'
    region:
      static: ap-northeast-2
