spring:
  thymeleaf:
    cache: 'false'
  servlet:
    multipart:
    max-request-size: 10MB
    max-file-size: 10MB
jpa:
  properties:
    hibernate:
    format_sql: 'true'
    use_sql_comments: 'true'
  hibernate:
    ddl-auto: update
  show-sql: 'true'
