jwt:
  secret:
    key: ${{ secrets.JWT_SECRET_KEY }}

aws:
  cloud:
    credentials:
      accessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    s3:
      bucket: springboot-img
    region:
      static: ap-northeast-2
    stack-auto: false

spring:
  datasource:
    url: jdbc:mysql://springboot-db.c9l2rqqpo7fr.ap-northeast-2.rds.amazonaws.com:3306/pol
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${{secrets.MYSQL_USERNAME}}
    password: ${{secrets.MYSQL_PW}}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    cache: false
