spring:
  profiles:
    include: aws
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: true
  thymeleaf:
    cache: 'false'
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB   #원하는 파일 크기로 설정
---
#Redis 접속
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  #캐시 설정
  cache:
    type: redis
    #캐시 만료 시간 (10분)
    redis:
      time-to-live: 600000